[project]
name = 'Decentralized-Financial-Planning-Scenario-Analysis'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.analysis-management]
path = 'contracts/analysis-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.decision-support]
path = 'contracts/decision-support.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
